### ISSUE TITLE
ValueError: No JSON object could be decoded

### ISSUE THREAD

**Issue by dabeeeenster** [yaybu/yaybu#123] opened 2013-11-08 16:19 UTC
See https://gist.github.com/dabeeeenster/9ad2803a2a2a734a05ad

**Comment by Jc2k** [comment] 2013-11-11 18:16
Well this is certainly a weird one.

I can reproduce this, and a workaround is to use `ubuntu` as the user instead of `root`. That's actually part of the fix too.

It turns out the image is letting you authenticate as root and is then allowing ssh client to submit a command to execute. It then claims that the command was executed successfully. However as far as i can tell it is actually just printing "You should login as the ubuntu user" to stdout/err rather than actually running your command.

This is fooling yaybu into believing a file is there that isn't, and when it tries to get the contents of the file its getting "You should login as..." - which isn't valid JSON!

Unfortunately because it isn't rejecting the authentication as one would expect if implementing the ssh protocol there isn't a good way to tell that the user name is wrong. The best I can do is to test execute `/bin/true` and `/bin/false` before running any real commands.

**Comment by Jc2k** [comment] 2013-11-12 08:47
With that commit in place I now see the following with your `Yaybufile`:

```
[*] Testing 'foo.j2' exists and is a valid template...                                                                                                                                              
[*] Testing compute credentials/connectivity                                                                                                                                                        
[ ] Connecting to 'ec2-54-217-164-116.eu-west-1.compute.amazonaws.com'                                                                                                                              
Got unusable SSH connection: Expected root, but 'whoami' returned: Please login as the user "ubuntu" rather than the user "root".
```

**Comment by dabeeeenster** [comment] 2013-11-12 14:05
So if I edit my file to be:

```
    user: ubuntu
```

Then this works - so not sure if this can be closed?

**Comment by Jc2k** [comment] 2013-11-12 22:49
I think we can close it - you are unstuck and i've landed the change in master ready for the next release.

**Closed as completed by Jc2k** 2013-11-12 22:49 UTC
